site_name: azmlclient
# site_description: 'A short description of my project'
repo_url: https://github.com/smarie/python-azureml-client
# docs_dir: .
# site_dir: ../site
# default branch is main instead of master now on github
edit_uri : ./edit/main/docs
nav:
    - Home: index.md
    - Changelog: changelog.md

theme: material  # readthedocs  mkdocs

markdown_extensions:
  - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true